---
driver: 
  name: terraform
  root_module_directory: test/fixtures/default

provisioner: 
  name: terraform

verifier:
  name : terraform
  groups: 
    - name: default
      controls: 
        - gcs

suites: 
  - name : "default"

platforms:
  - name : terraform
      
